CREATE TABLE IF NOT EXISTS edges (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  src UUID NOT NULL REFERENCES links(id) ON DELETE CASCADE,
  dst UUID NOT NULL REFERENCES links(id) ON DELETE CASCADE,
  updated_at TIMESTAMP,
  CONSTRAINT edges_links UNIQUE(src,dst)
);