// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/IkehAkinyemi/fishstick-engine/crawler (interfaces: URLGetter,PrivateNetworkDetector,Graph,Indexer)
//
// Generated by this command:
//
//	mockgen -package mocks -destination mocks/mocks.go github.com/IkehAkinyemi/fishstick-engine/crawler URLGetter,PrivateNetworkDetector,Graph,Indexer
//

// Package mocks is a generated GoMock package.
package mocks

import (
	http "net/http"
	reflect "reflect"
	time "time"

	graph "github.com/IkehAkinyemi/fishstick-engine/linkgraph/graph"
	index "github.com/IkehAkinyemi/fishstick-engine/textindexer/index"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockURLGetter is a mock of URLGetter interface.
type MockURLGetter struct {
	ctrl     *gomock.Controller
	recorder *MockURLGetterMockRecorder
	isgomock struct{}
}

// MockURLGetterMockRecorder is the mock recorder for MockURLGetter.
type MockURLGetterMockRecorder struct {
	mock *MockURLGetter
}

// NewMockURLGetter creates a new mock instance.
func NewMockURLGetter(ctrl *gomock.Controller) *MockURLGetter {
	mock := &MockURLGetter{ctrl: ctrl}
	mock.recorder = &MockURLGetterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockURLGetter) EXPECT() *MockURLGetterMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockURLGetter) Get(url string) (*http.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", url)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockURLGetterMockRecorder) Get(url any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockURLGetter)(nil).Get), url)
}

// MockPrivateNetworkDetector is a mock of PrivateNetworkDetector interface.
type MockPrivateNetworkDetector struct {
	ctrl     *gomock.Controller
	recorder *MockPrivateNetworkDetectorMockRecorder
	isgomock struct{}
}

// MockPrivateNetworkDetectorMockRecorder is the mock recorder for MockPrivateNetworkDetector.
type MockPrivateNetworkDetectorMockRecorder struct {
	mock *MockPrivateNetworkDetector
}

// NewMockPrivateNetworkDetector creates a new mock instance.
func NewMockPrivateNetworkDetector(ctrl *gomock.Controller) *MockPrivateNetworkDetector {
	mock := &MockPrivateNetworkDetector{ctrl: ctrl}
	mock.recorder = &MockPrivateNetworkDetectorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPrivateNetworkDetector) EXPECT() *MockPrivateNetworkDetectorMockRecorder {
	return m.recorder
}

// IsPrivate mocks base method.
func (m *MockPrivateNetworkDetector) IsPrivate(host string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsPrivate", host)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsPrivate indicates an expected call of IsPrivate.
func (mr *MockPrivateNetworkDetectorMockRecorder) IsPrivate(host any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsPrivate", reflect.TypeOf((*MockPrivateNetworkDetector)(nil).IsPrivate), host)
}

// MockGraph is a mock of Graph interface.
type MockGraph struct {
	ctrl     *gomock.Controller
	recorder *MockGraphMockRecorder
	isgomock struct{}
}

// MockGraphMockRecorder is the mock recorder for MockGraph.
type MockGraphMockRecorder struct {
	mock *MockGraph
}

// NewMockGraph creates a new mock instance.
func NewMockGraph(ctrl *gomock.Controller) *MockGraph {
	mock := &MockGraph{ctrl: ctrl}
	mock.recorder = &MockGraphMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGraph) EXPECT() *MockGraphMockRecorder {
	return m.recorder
}

// RemoveStaleEdge mocks base method.
func (m *MockGraph) RemoveStaleEdge(fromID uuid.UUID, updatedBefore time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveStaleEdge", fromID, updatedBefore)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveStaleEdge indicates an expected call of RemoveStaleEdge.
func (mr *MockGraphMockRecorder) RemoveStaleEdge(fromID, updatedBefore any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveStaleEdge", reflect.TypeOf((*MockGraph)(nil).RemoveStaleEdge), fromID, updatedBefore)
}

// UpsertEdge mocks base method.
func (m *MockGraph) UpsertEdge(edge *graph.Edge) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertEdge", edge)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertEdge indicates an expected call of UpsertEdge.
func (mr *MockGraphMockRecorder) UpsertEdge(edge any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertEdge", reflect.TypeOf((*MockGraph)(nil).UpsertEdge), edge)
}

// UpsertLink mocks base method.
func (m *MockGraph) UpsertLink(link *graph.Link) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertLink", link)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertLink indicates an expected call of UpsertLink.
func (mr *MockGraphMockRecorder) UpsertLink(link any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertLink", reflect.TypeOf((*MockGraph)(nil).UpsertLink), link)
}

// MockIndexer is a mock of Indexer interface.
type MockIndexer struct {
	ctrl     *gomock.Controller
	recorder *MockIndexerMockRecorder
	isgomock struct{}
}

// MockIndexerMockRecorder is the mock recorder for MockIndexer.
type MockIndexerMockRecorder struct {
	mock *MockIndexer
}

// NewMockIndexer creates a new mock instance.
func NewMockIndexer(ctrl *gomock.Controller) *MockIndexer {
	mock := &MockIndexer{ctrl: ctrl}
	mock.recorder = &MockIndexerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIndexer) EXPECT() *MockIndexerMockRecorder {
	return m.recorder
}

// Index mocks base method.
func (m *MockIndexer) Index(doc *index.Document) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Index", doc)
	ret0, _ := ret[0].(error)
	return ret0
}

// Index indicates an expected call of Index.
func (mr *MockIndexerMockRecorder) Index(doc any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Index", reflect.TypeOf((*MockIndexer)(nil).Index), doc)
}
